function cambiarfondo1(){document.getElementById('header').style.backgroundColor = 'black'
document.getElementById('header').style.color = 'white'
document.getElementById('navbar').style.color ='black'
document.getElementById('main').style.backgroundColor = 'black'
document.getElementById('main').style.color ='white'
document.getElementById('section').style.backgroundColor = 'black'
document.getElementById('section').style.color = 'white'
document.getElementById('card1').style.backgroundColor ='black'
document.getElementById('card1').style.color ='white'
document.getElementById('card2').style.backgroundColor ='black'
document.getElementById('card2').style.color ='white'
document.getElementById('card3').style.backgroundColor ='black'
document.getElementById('card3').style.color ='white'
document.getElementById('card4').style.backgroundColor ='black'
document.getElementById('card4').style.color ='white'
document.getElementById('footer').style.backgroundColor = 'black'
document.getElementById('footer').style.color = 'white';}

function cambiarfondo2(){document.getElementById('header').style.backgroundColor = 'white'
document.getElementById('header').style.color = 'black'
document.getElementById('navbar').style.color ='black'
document.getElementById('main').style.backgroundColor = 'white'
document.getElementById('main').style.color ='black'
document.getElementById('section').style.backgroundColor = 'white'
document.getElementById('section').style.color = 'black'
document.getElementById('card1').style.backgroundColor ='white'
document.getElementById('card1').style.color ='black'
document.getElementById('card2').style.backgroundColor ='white'
document.getElementById('card2').style.color ='black'
document.getElementById('card3').style.backgroundColor ='white'
document.getElementById('card3').style.color ='black'
document.getElementById('card4').style.backgroundColor ='white'
document.getElementById('card4').style.color ='black'
document.getElementById('footer').style.backgroundColor = 'white'
document.getElementById('footer').style.color = 'black';}

function alertcopyright(){alert("Página desarrollada por Lola Torres Rodriguez. \n Contacto: lolatorresrodr@gmail.com");}